// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ID_CMD_TAB_HOME 2 
#define ID_CMD_TAB_HOME_LabelTitle_RESID 200
#define ID_CMD_TAB_HOME_Keytip_RESID 60001
#define cmdShapesGroup 3 
#define cmdShapesGroup_LabelTitle_RESID 210
#define cmdStylesGroup 4 
#define cmdStylesGroup_LabelTitle_RESID 213
#define cmdColorsGroup 5 
#define cmdColorsGroup_LabelTitle_RESID 211
#define cmdColorPicker 6 
#define cmdColorPicker_LabelTitle_RESID 220
#define cmdColorPicker_LargeImages_RESID 241
#define cmdColorFillPicker 7 
#define cmdColorFillPicker_LabelTitle_RESID 221
#define cmdColorFillPicker_LargeImages_RESID 242
#define IDR_CMD_SHAPES 8 
#define IDR_CMD_SHAPES_LabelTitle_RESID 240
#define ID_CMD_STYLE 9 
#define ID_CMD_STYLE_LabelTitle_RESID 60002
#define ID_CMD_STYLE_LargeImages_RESID 250
#define ID_CMD_STYLE_SOLID 10 
#define ID_CMD_STYLE_SOLID_LabelTitle_RESID 60003
#define ID_CMD_STYLE_SOLID_LargeImages_RESID 251
#define ID_CMD_STYLE_DASH 11 
#define ID_CMD_STYLE_DASH_LabelTitle_RESID 60004
#define ID_CMD_STYLE_DASH_LargeImages_RESID 252
#define ID_CMD_STYLE_DOT 12 
#define ID_CMD_STYLE_DOT_LabelTitle_RESID 60005
#define ID_CMD_STYLE_DOT_LargeImages_RESID 253
#define ID_CMD_STYLE_DASHDOT 13 
#define ID_CMD_STYLE_DASHDOT_LabelTitle_RESID 60006
#define ID_CMD_STYLE_DASHDOT_LargeImages_RESID 254
#define ID_CMD_STYLE_DASHDOTDOT 14 
#define ID_CMD_STYLE_DASHDOTDOT_LabelTitle_RESID 60007
#define ID_CMD_STYLE_DASHDOTDOT_LargeImages_RESID 255
#define ID_CMD_WIDTH 15 
#define ID_CMD_WIDTH_LabelTitle_RESID 60008
#define ID_CMD_WIDTH_LargeImages_RESID 260
#define IDR_CMD_BORDERSIZES 16 
#define IDR_CMD_BORDERSIZES_LabelTitle_RESID 270
#define ID_CMD_SIZE_1 17 
#define ID_CMD_SIZE_1_LabelTitle_RESID 60009
#define ID_CMD_SIZE_1_LargeImages_RESID 271
#define ID_CMD_SIZE_2 18 
#define ID_CMD_SIZE_2_LabelTitle_RESID 60010
#define ID_CMD_SIZE_2_LargeImages_RESID 272
#define ID_CMD_SIZE_3 19 
#define ID_CMD_SIZE_3_LabelTitle_RESID 60011
#define ID_CMD_SIZE_3_LargeImages_RESID 273
#define ID_CMD_SIZE_5 20 
#define ID_CMD_SIZE_5_LabelTitle_RESID 60012
#define ID_CMD_SIZE_5_LargeImages_RESID 274
#define ID_CMD_LINE 21 
#define ID_CMD_LINE_LabelTitle_RESID 60013
#define ID_CMD_LINE_LargeImages_RESID 300
#define ID_CMD_RECTANGLE 22 
#define ID_CMD_RECTANGLE_LabelTitle_RESID 60014
#define ID_CMD_RECTANGLE_LargeImages_RESID 301
#define ID_CMD_ELLIPSE 23 
#define ID_CMD_ELLIPSE_LabelTitle_RESID 60015
#define ID_CMD_ELLIPSE_LargeImages_RESID 302
#define ID_CMD_NEW 24 
#define ID_CMD_NEW_LabelTitle_RESID 60016
#define ID_CMD_NEW_LabelDescription_RESID 60017
#define ID_CMD_NEW_TooltipTitle_RESID 60018
#define ID_CMD_NEW_TooltipDescription_RESID 60019
#define ID_CMD_NEW_LargeImages_RESID 101
#define ID_CMD_OPEN 25 
#define ID_CMD_OPEN_LabelTitle_RESID 60020
#define ID_CMD_OPEN_LabelDescription_RESID 60021
#define ID_CMD_OPEN_TooltipTitle_RESID 60022
#define ID_CMD_OPEN_TooltipDescription_RESID 60023
#define ID_CMD_OPEN_LargeImages_RESID 102
#define ID_CMD_SAVE 26 
#define ID_CMD_SAVE_LabelTitle_RESID 60024
#define ID_CMD_SAVE_LabelDescription_RESID 60025
#define ID_CMD_SAVE_TooltipTitle_RESID 60026
#define ID_CMD_SAVE_TooltipDescription_RESID 60027
#define ID_CMD_SAVE_LargeImages_RESID 103
#define ID_CMD_EXIT 27 
#define ID_CMD_EXIT_LabelTitle_RESID 60028
#define ID_CMD_EXIT_LabelDescription_RESID 60029
#define ID_CMD_EXIT_TooltipTitle_RESID 60030
#define ID_CMD_EXIT_TooltipDescription_RESID 60031
#define ID_CMD_EXIT_LargeImages_RESID 104
#define ID_CMD_UNDO 28 
#define ID_CMD_UNDO_LabelTitle_RESID 60032
#define ID_CMD_UNDO_LabelDescription_RESID 60033
#define ID_CMD_UNDO_TooltipTitle_RESID 60034
#define ID_CMD_UNDO_TooltipDescription_RESID 60035
#define ID_CMD_UNDO_LargeImages_RESID 105
#define ID_CMD_REDO 29 
#define ID_CMD_REDO_LabelTitle_RESID 60036
#define ID_CMD_REDO_LabelDescription_RESID 60037
#define ID_CMD_REDO_TooltipTitle_RESID 60038
#define ID_CMD_REDO_TooltipDescription_RESID 60039
#define ID_CMD_REDO_LargeImages_RESID 106
#define ID_CMD_HELP 30 
#define ID_CMD_HELP_LabelDescription_RESID 60040
#define ID_CMD_HELP_TooltipTitle_RESID 60041
#define ID_CMD_HELP_TooltipDescription_RESID 60042
#define ID_QAT 40000 
#define ID_CUSTOM_QAT 40001 
#define InternalCmd2_LabelTitle_RESID 60043
